#!/bin/bash


# Get the system information
username=$(whoami)
datetime=$(date +"%Y-%m-%d %H:%M:%S")
hostname=$(hostname)
distro=$(lsb_release -d | cut -f2-)
uptime=$(uptime -p)

# Get the hardware information
cpu_info=$(lscpu | grep "Model name:" | cut -d':' -f2 )
cpu_cur_speed=$(lshw -c processor | grep "size:" | uniq)
cpu_max_speed=$(lshw -c processor | grep "capacity:" | uniq)
ram_size=$(free -h | grep "Mem:")
disk_info=$(lsblk -So NAME,MODEL,SIZE  )
video_card=$(lspci | grep VGA )

# Get the network information
fqdn=$(hostname -f)
host_address=$(hostname -I )
gateway_ip=$(ip route | grep default | awk '{print $3}')
dns_server=$(cat /etc/resolv.conf | grep "nameserver")
interface_info=$(ip r | grep "default" | awk '{print $5}' )
ip_address=$(ip a | grep -w inet |grep -v '127.0.0.1' | awk '{print $2}' )

# Get the system status
logged_in_users=$(who | cut -d' ' -f1)
disk_space=$(df -h | awk '{print $6,$4}')
process_count=$(ps aux | wc -l)
load_averages=$(cat /proc/loadavg )
memory_allocation=$(free -h | grep "Mem:" | awk '{print "Total:", $2, "Used:", $3, "Free:", $4}')
listening_ports=$(netstat -ltU | grep 'LISTEN'  )
ufw_rules=$(ufw status )

# Create the system report
echo "
System Report generated by $username, $datetime

System Information
------------------
Hostname: $hostname
OS: $distro
Uptime: $uptime

Hardware Information
--------------------
CPU: $cpu_info
Speed: $cpu_cur_speed  $cpu_max_speed
RAM: $ram_size
Disk(s): $disk_info
Video: $video_card

/Network Information
-------------------
FQDN: $fqdn
Host Address: $host_address
Gateway IP: $gateway_ip
DNS Server: $dns_server
Interface Name: $interface_info
IP Address: $ip_address

System Status
-------------
Users Logged In: ${logged_in_users%, }
Disk Space: $disk_space
Process Count: $process_count
Load Averages: $load_averages
Memory Allocation: $memory_allocation
Listening Network Ports: ${listening_ports%, }
UFW Rules: $ufw_rules
EOL
"

